all:
	sass --watch \
	sass/login.sass:login.css \
	sass/admin.sass:admin.css \
	sass/write.sass:write.css \
	sass/author.sass:author.css \
	sass/settings.sass:settings.css \
	sass/password.sass:password.css \
	--style compressed

clean:
	rm -rf *.css
