all:
	sass --watch \
	sass/login.sass:login.css \
	sass/admin.sass:admin.css \
	sass/write.sass:write.css \
	sass/author.sass:author.css \
	sass/settings.sass:settings.css \
	sass/password.sass:password.css \
	sass/edit.sass:edit.css \
	sass/drafts.sass:drafts.css \
	sass/404.sass:404.css \
	sass/public.sass:public.css \
	sass/post.sass:post.css \
	--style compressed

clean:
	rm -rf *.css
